# Generated by Django 4.1.5 on 2023-01-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='ListeQuestion',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ennonce',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reponse',
        ),
    ]
